<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the raw (non-ORM-mapped) table expected by Symfony's Doctrine-backed
 * persistent remember-me token provider.
 *
 * Not generated by doctrine:migrations:diff: this installed version of
 * symfony/doctrine-bridge does not wire DoctrineTokenProvider's schema into
 * doctrine-bundle's schema tooling, so this table must be created by hand.
 * Column names/types match DoctrineTokenProvider exactly.
 */
final class Version20260903163300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create rememberme_token table for persistent remember-me login.';
    }

    public function isTransactional(): bool
    {
        // MySQL DDL implicitly commits; an explicit wrapping transaction just
        // triggers a deprecated "already committed" silencing path.
        return false;
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE rememberme_token (series CHAR(88) NOT NULL, value CHAR(88) NOT NULL, lastUsed DATETIME NOT NULL, class VARCHAR(100) NOT NULL DEFAULT \'\', username VARCHAR(200) NOT NULL, PRIMARY KEY (series)) DEFAULT CHARACTER SET utf8mb4');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE rememberme_token');
    }
}
